import { launch, login, base, shots, ok } from "./_lib.mjs";
const { browser, page } = await launch();
await login(page);
page.on("dialog", async (d) => { console.log("DIALOG:", d.message()); await d.accept(); });
page.on("response", async (r) => { if (r.url().includes("/move")) console.log("MOVE", r.status(), await r.text()); });
page.on("request", (r) => { if (r.url().includes("/move")) console.log("REQ", r.postData()); });
await page.goto(base + "/deals");
const card = page.locator("[data-testid=kanban-card]").first();
const id = await card.getAttribute("data-deal");
const lostCol = page.locator("[data-testid=kanban-col][data-stage-name=Lost] [data-column]");
await lostCol.scrollIntoViewIfNeeded(); await card.scrollIntoViewIfNeeded();
const cb = await card.boundingBox(); const lb = await lostCol.boundingBox();
console.log("card", cb, "lost", lb);
await page.mouse.move(cb.x + cb.width / 2, cb.y + 20); await page.mouse.down();
await page.mouse.move(cb.x + cb.width / 2 + 10, cb.y + 30, { steps: 5 });
await page.mouse.move(lb.x + lb.width / 2, lb.y + 40, { steps: 15 });
await page.mouse.up();
await page.waitForTimeout(2000);
console.log("dialog open:", await page.evaluate(() => document.getElementById("lost-reason-dialog").open), "url", page.url());
await page.screenshot({ path: `${shots}/dbg-kanban.png` });
await browser.close();
