import { launch, login, base, shots, ok } from "./_lib.mjs";
const { browser, page } = await launch({ width: 2600 });
await login(page);
page.on("dialog", async (d) => { console.log("DIALOG:", d.message()); await d.accept(); });
page.on("response", async (r) => { if (r.url().includes("/move")) console.log("MOVE", r.status(), await r.text()); });
await page.goto(base + "/deals");
const card = page.locator("[data-testid=kanban-col][data-stage-name='Proposal Sent'] [data-testid=kanban-card]").first();
console.log("cards in Proposal Sent:", await page.locator("[data-testid=kanban-col][data-stage-name='Proposal Sent'] [data-testid=kanban-card]").count());
const lostCol = page.locator("[data-testid=kanban-col][data-stage-name=Lost] [data-column]");
await page.evaluate(() => { const b = document.querySelector("[data-kanban]"); b.scrollLeft = b.scrollWidth; });
console.log("board", await page.evaluate(() => { const b = document.querySelector("[data-kanban]"); return [b.scrollLeft, b.scrollWidth, b.clientWidth]; }));
const cb = await card.boundingBox(); const lb = await lostCol.boundingBox();
console.log("card", cb, "lost", lb, "viewport", page.viewportSize());
await page.mouse.move(cb.x + cb.width / 2, cb.y + 20); await page.mouse.down();
await page.mouse.move(cb.x + cb.width / 2 + 10, cb.y + 30, { steps: 5 });
await page.mouse.move(lb.x + lb.width / 2, lb.y + 40, { steps: 15 });
await page.mouse.up();
await page.waitForTimeout(2000);
console.log("dialog open:", await page.evaluate(() => document.getElementById("lost-reason-dialog").open), "url", page.url());
await page.screenshot({ path: `${shots}/dbg-kanban2.png` });
await browser.close();
