import { launch, login, base, shots, ok } from "./_lib.mjs";
const { browser, page } = await launch({ width: 2600 });
const N = Date.now();
await login(page);
page.on("request", (r) => { if (r.url().includes("/move")) console.log("REQ", r.postData()); });
page.on("response", async (r) => { if (r.url().includes("/move")) console.log("MOVE", r.status(), (await r.text()).replace(/\s+/g, " ")); });
await page.goto(base + "/deals");
await page.click("[data-open=deal-dialog]");
await page.fill("#deal-dialog #title", `Dbg ${N}`);
await page.fill("#deal-dialog #amount", "5000");
await page.click("#deal-dialog button[type=submit]");
await page.waitForURL("**/deals/*");
page.once("dialog", async (d) => { console.log("DIALOG", d.message()); await d.accept(); });
await page.selectOption("[data-stage-select]", { label: "Proposal Sent (60%)" });
await page.waitForTimeout(1500);
console.log("url now", page.url(), "select", await page.inputValue("[data-stage-select]"));
await page.selectOption("[data-stage-select]", { label: "Qualified (40%)" });
await page.waitForTimeout(1500);
console.log("url now", page.url(), "select", await page.inputValue("[data-stage-select]"));
await browser.close();
