import { launch, login, base, shots, ok } from "./_lib.mjs";
const { browser, page } = await launch({ width: 2600 });
const N = Date.now();
await login(page);
page.on("request", (r) => { if (r.url().includes("/move")) console.log("REQ", r.postData()); });
page.on("response", async (r) => { if (r.url().includes("/move")) console.log("MOVE", r.status()); });
await page.goto(base + "/deals");
await page.click("[data-open=deal-dialog]");
await page.fill("#deal-dialog #title", `Dbg ${N}`);
await page.click("#deal-dialog button[type=submit]");
await page.waitForURL("**/deals/*");
page.once("dialog", async (d) => { console.log("DIALOG", d.message()); await d.accept(); });
const mv1 = page.waitForResponse((r) => r.url().includes("/move"));
await page.selectOption("[data-stage-select]", { label: "Proposal Sent (60%)" });
await mv1; await page.waitForTimeout(800);
console.log("after alert url", page.url());
await page.click("[data-tab=items]");
await page.click("[data-add-row]");
await page.fill("[data-line-items] tbody input[name$='[name]']", "Custom");
await page.fill("[data-line-items] tbody input[name$='[unit_price]']", "1000");
await page.click("[data-line-items] button[type=submit]");
await page.waitForSelector("[data-testid=form-success]");
console.log("after save url", page.url(), "selects:", await page.evaluate(() => [document.querySelectorAll("[data-stage-select]").length, typeof postJSON, document.readyState]));
console.log("select value", await page.inputValue("[data-stage-select]"));
await page.selectOption("[data-stage-select]", { label: "Proposal Sent (60%)" });
await page.waitForTimeout(1500);
console.log("select value after", await page.inputValue("[data-stage-select]"), page.url());
await page.screenshot({ path: `${shots}/dbg6.png` });
await browser.close();
